### ISSUE TITLE
Issue with media

### ISSUE THREAD

**Issue by victorcea87** [KevinJump/jumps.umbraco.usync#57]
Hi,

Am I the unique person who is having a lot of issues with the sync of the Media folder? If I have files inside folders and some items of a different media type it creates the files in Umbraco with wrong id's.

Could someone help me?

Thanks!

**Comment by KevinJump** [comment]
Hi, 

which version of usync are you using?

**Comment by victorcea87** [comment]
Hi Kevin,

It's 3.1.1.740

**Comment by KevinJump** [comment]
Hi

for the newer vesions (v3+) I think setting moveMedia=false in the config/usynccore.config file is better. 

This will make usync only copy the db bits, and expect you to move the /media folder. that way subfolders and files and stuff shouldn't be an issue, because all usync does is move the properties that are in the db.  

There can be quite a lot of /media/1292/ type folders directly referenced inside content, and usync doesn't capture all of these, so just copying the media folder is better for them. 

i am also doing a bit of work on media mapping (https://github.com/KevinJump/uSync/issues/32) so i will have a bit of a test and see if there is anything else i can add. 

Kevin

**Comment by victorcea87** [comment]
I don't understand how we should do it, I'm going to explain you our case and see what you think and if we are doing it fine.
We have a project in Umbraco uploaded to our TFSOnline (we use visual studio). We are not added anything in the Media folder (not the usync media folder), we are just adding the content (included images) in the usync folder. We are using an Umbraco plane db (just the db that Umbraco creates when it is installed), as usync should import everything this is why we are doing that and we avoid to do anything with the db.
Now the doubt that we have is if we are doing it fine or not and about the media issue I don't know if we should keep the media folder with the images (the media folder in the root) and remove all from media usync and set moveMedia to false or what we should do.

Suggestions?

**Comment by KevinJump** [comment]
Hi

Yes by default when you save anything in umbraco uSync will create a corresponding file for the db settings in the usync folder. You don't need to manually put anything in the usync folder, as it does this on saves, and when you ask it to do an export.

When you copy between sites, you need to copy the usync(/data) folder and the bits of umbraco that are not in the DB (e.g. views, css, scripts...)

Media is a bit different because when you add media in umbraco - umbraco will put the files in /media/**nnnn**/file.name where nnnn is just an incrementing number. It will also store some details in the db (things like name, and size etc) this will be given an internal DB id in umbraco (which is not the same as the number of the folder). 

uSync's default behavior is to create a file in /media/ for the db bits, (this is the def.config file) and also copy the actual media to a sub folder - this is because previous to v7 you could never know what the **nnnn** value was going to be on the other side. 

however the way the nnnn number is generated has changed in v7 (it's not some random db value anymore, it's based on existing folders). this makes it potentially a lot simpler for usync to only save the DB bits to a file and then not try to import the actual media files but just assume they are there. 

this is the movemedia setting (it is basically saying don't move the media into the usync folder) 

so if you have moveMedia = false
- you will still get and need /usync/data/media/ 
- the /usync/data/media/ folder will no longer contain the actual media files, just the settings
- when you copy between sites, copy the /media/ folder over as well as the usync folder
- when usync does the import, it won't attempt to do anything clever with the the /media/nnnn/ values it will just create/sync the media db bits. 
- any values in the site that are like "/media/nnnn/filename.jpg" will still just work, because you copied the media folder.

**Comment by victorcea87** [comment]
Understood. And what will happen with the media types? They are not images, they are items and they are not in the /media/ folder so not sure how I should add them :(

**Comment by KevinJump** [comment]
Hi

When you create mediatypes they should end up with a .config file in the usync/data/mediatype folder. 

If you have ExportAtStartup = true in the usyncbackoffice.config file (which is the default) all of this should just happen automatically without you having to worry about it.

**Comment by victorcea87** [comment]
Great perfect, I will try it :)

**Comment by victorcea87** [comment]
I mean the media file that I create which is not an image, is a media based on a media type (like a document type but in media), they don't have images, they are not in the /media/ folder, in usync/media/ folder is just a .config file without image because it doesn't have.

**Comment by KevinJump** [comment]
yeah, but there should be some files in /media/ for those items . ? any media you add to umbraco should end up in /media/ regardless of filetype.

**Comment by victorcea87** [comment]
Unfortunately no, in /media/ there are just the images, not that type of media :( I have just test it and I think I'm right

**Comment by KevinJump** [comment]
yeah - there is something else going then, all files in the your media section no matter what extension should end up in the /media folder. irrespective of usync.

**Comment by victorcea87** [comment]
ah yes, you are right! They are not exactly in /media/ folder because they are not images but they are in somewhere because I can see them in Umbraco :)

Thanks Kevin!

**Comment by victorcea87** [comment]
Hi Kevin,

I'm having a lot of problems with the images importing with uSync. I'm doing what you said me, it means put the media importing to false and leaving the images in the root media folder (in the uSync>Data>Media I just have the configs). The problem what I'm having now is that I'm doing a full import and the images are created in the media tab in Umbraco but they are not visible, is very strange, I can see the item in the media tab but when I access the image doesn't appear and the website doesn't charge them neither.

Any thoughts?

Thanks!

**Comment by KevinJump** [comment]
Continuation of this on other repo (part of #61?)

See: https://github.com/KevinJump/uSync/issues/45
